<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../xsd/GetPersonData_sp.xsd"/>
      <rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/GetPersonData"/>
      <param name="outputParameters" />
    </source>
    <source type="XSD">
      <schema location="../xsd/ChangeRequestPayload.xsd"/>
      <rootElement name="ChangeRequest" namespace="http://services.cap.org/interfaces/myaccount/ChangeRequest"/>
      <param name="changeRequestObject" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/ChangeRequestPayload.xsd"/>
      <rootElement name="ChangeRequest" namespace="http://services.cap.org/interfaces/myaccount/ChangeRequest"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU OCT 16 17:00:44 CDT 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:cp="http://services.cap.org/interfaces/myaccount/ChangeRequest"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:comm="http://services.cap.org/interfaces/commontypes"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:hdr="http://services.cap.org/interfaces/header"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/GetPersonData"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl cp comm hdr db xsd bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:param name="changeRequestObject"/>
  <xsl:template match="/">
    <cp:ChangeRequest>
      <hdr:InterfaceHeader>
        <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:MessageID">
          <hdr:MessageID>
            <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:MessageID"/>
          </hdr:MessageID>
        </xsl:if>
        <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:MessageName">
          <hdr:MessageName>
            <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:MessageName"/>
          </hdr:MessageName>
        </xsl:if>
        <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:CreatedBy">
          <hdr:CreatedBy>
            <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:CreatedBy"/>
          </hdr:CreatedBy>
        </xsl:if>
        <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:CreationDateTime">
          <hdr:CreationDateTime>
            <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:CreationDateTime"/>
          </hdr:CreationDateTime>
        </xsl:if>
        <hdr:Sender>
          <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Sender/hdr:Name">
            <hdr:Name>
              <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Sender/hdr:Name"/>
            </hdr:Name>
          </xsl:if>
          <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Sender/hdr:ApplicationName">
            <hdr:ApplicationName>
              <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Sender/hdr:ApplicationName"/>
            </hdr:ApplicationName>
          </xsl:if>
          <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Sender/hdr:TaskLevel">
            <hdr:TaskLevel>
              <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Sender/hdr:TaskLevel"/>
            </hdr:TaskLevel>
          </xsl:if>
          <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Sender/hdr:InstanceID">
            <hdr:InstanceID>
              <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Sender/hdr:InstanceID"/>
            </hdr:InstanceID>
          </xsl:if>
          <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Sender/hdr:UserID">
            <hdr:UserID>
              <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Sender/hdr:UserID"/>
            </hdr:UserID>
          </xsl:if>
        </hdr:Sender>
        <hdr:Target>
          <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Target/hdr:Name">
            <hdr:Name>
              <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Target/hdr:Name"/>
            </hdr:Name>
          </xsl:if>
          <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Target/hdr:ApplicationName">
            <hdr:ApplicationName>
              <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Target/hdr:ApplicationName"/>
            </hdr:ApplicationName>
          </xsl:if>
          <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Target/hdr:Endpoint">
            <hdr:Endpoint>
              <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Target/hdr:Endpoint"/>
            </hdr:Endpoint>
          </xsl:if>
          <xsl:if test="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Target/hdr:UserID">
            <hdr:UserID>
              <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/hdr:InterfaceHeader/hdr:Target/hdr:UserID"/>
            </hdr:UserID>
          </xsl:if>
        </hdr:Target>
      </hdr:InterfaceHeader>
      <cp:RequestCode>
        <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/cp:RequestCode"/>
      </cp:RequestCode>
      <cp:RequestTitle>
        <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/cp:RequestTitle"/>
      </cp:RequestTitle>
      <cp:Priority>
        <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/cp:Priority"/>
      </cp:Priority>
      <cp:RequestDate>
        <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/cp:RequestDate"/>
      </cp:RequestDate>
      <cp:RequestedBy>
        <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/cp:RequestedBy"/>
      </cp:RequestedBy>
      <cp:Action>
        <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/cp:Action"/>
      </cp:Action>
      <cp:SendData>
        <cp:PartyId>
          <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/cp:SendData/cp:PartyId"/>
        </cp:PartyId>
        <xsl:for-each select="$changeRequestObject/cp:ChangeRequest/cp:SendData/cp:DataItem">
          <cp:DataItem>
            <xsl:if test="cp:Name">
              <cp:Name>
                <xsl:value-of select="cp:Name"/>
              </cp:Name>
            </xsl:if>
            <xsl:if test="cp:OldValue">
              <cp:OldValue>
                <xsl:value-of select="cp:OldValue"/>
              </cp:OldValue>
            </xsl:if>
            <xsl:if test="cp:NewValue">
              <cp:NewValue>
                <xsl:value-of select="cp:NewValue"/>
              </cp:NewValue>
            </xsl:if>
            <xsl:if test="cp:DataType">
              <cp:DataType>
                <xsl:value-of select="cp:DataType"/>
              </cp:DataType>
            </xsl:if>
          </cp:DataItem>
        </xsl:for-each>
      </cp:SendData>
      <cp:Comments>
        <xsl:value-of select="$changeRequestObject/cp:ChangeRequest/cp:Comments"/>
      </cp:Comments>
      <cp:Person>
        <comm:PartyID>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PARTY_ID"/>
        </comm:PartyID>
        <comm:PartyNumber>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PARTY_NUMBER"/>
        </comm:PartyNumber>
        <comm:Status>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:STATUS"/>
        </comm:Status>
        <comm:FirstName>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:FIRST_NAME"/>
        </comm:FirstName>
        <comm:MiddleName>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:MIDDLE_NAME"/>
        </comm:MiddleName>
        <comm:LastName>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:LAST_NAME"/>
        </comm:LastName>
        <comm:NameSuffix>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:NAME_SUFFIX"/>
        </comm:NameSuffix>
        <comm:NickName>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:NICK_NAME"/>
        </comm:NickName>
        <comm:PersonTitle>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PERSON_TITLE"/>
        </comm:PersonTitle>
        <comm:DateOfBirth>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:DATE_OF_BIRTH"/>
        </comm:DateOfBirth>
        <comm:Gender>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:GENDER"/>
        </comm:Gender>
        <comm:IsMember>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:IS_MEMBER"/>
        </comm:IsMember>
        <comm:MemberType>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:MEMBER_TYPE"/>
        </comm:MemberType>
        <comm:MemberStatus>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:MEMBER_STATUS"/>
        </comm:MemberStatus>
        <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION">
          <comm:PrimaryInstitution>
            <comm:InstitutionID>
              <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:PARTY_ID"/>
            </comm:InstitutionID>
            <comm:InstitutionNumber>
              <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:PARTY_NUMBER"/>
            </comm:InstitutionNumber>
            <comm:InstitutionName>
              <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:PARTY_NAME"/>
            </comm:InstitutionName>
            <comm:InstitutionLBN>
              <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:LONG_BUSINESS_NAME"/>
            </comm:InstitutionLBN>
            <comm:CLIANumber>
              <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:CLIA_NUMBER"/>
            </comm:CLIANumber>
            <comm:LAPFlag>
              <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:LAP_FLAG"/>
            </comm:LAPFlag>
            <comm:HUFlag>
              <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:HU_FLAG"/>
            </comm:HUFlag>
            <comm:Address>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:PARTY_SITE_ID">
                <comm:PartySiteID>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:PARTY_SITE_ID"/>
                </comm:PartySiteID>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:LOCATION_ID">
                <comm:LocationID>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:LOCATION_ID"/>
                </comm:LocationID>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:COUNTRY">
                <comm:Country>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:COUNTRY"/>
                </comm:Country>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ADDRESS1">
                <comm:Address1>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ADDRESS1"/>
                </comm:Address1>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ADDRESS2">
                <comm:Address2>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ADDRESS2"/>
                </comm:Address2>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ADDRESS3">
                <comm:Address3>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ADDRESS3"/>
                </comm:Address3>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ADDRESS4">
                <comm:Address4>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ADDRESS4"/>
                </comm:Address4>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:CITY">
                <comm:City>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:CITY"/>
                </comm:City>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:STATE">
                <comm:State>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:STATE"/>
                </comm:State>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:PROVINCE">
                <comm:Province>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:PROVINCE"/>
                </comm:Province>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:COUNTY">
                <comm:County>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:COUNTY"/>
                </comm:County>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:POSTALCODE">
                <comm:PostalCode>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:POSTALCODE"/>
                </comm:PostalCode>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ADDRESSNAME">
                <comm:AddressName>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ADDRESSNAME"/>
                </comm:AddressName>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:IDENTIFINGFLAG">
                <comm:IdentifingFlag>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:IDENTIFINGFLAG"/>
                </comm:IdentifingFlag>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:PREFERREDFLAG">
                <comm:PreferredFlag>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:PREFERREDFLAG"/>
                </comm:PreferredFlag>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:STATUS">
                <comm:Status>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:STATUS"/>
                </comm:Status>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ISADDRESSVALIDATED">
                <comm:IsAddressValidated>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:ISADDRESSVALIDATED"/>
                </comm:IsAddressValidated>
              </xsl:if>
              <comm:Purposes>
                <xsl:for-each select="/db:OutputParameters/db:X_PERSON_DATA/db:PRIMARY_INSTITUTION/db:ADDRESS/db:PURPOSES/db:PURPOSES_ITEM">
                  <comm:Purpose>
                    <xsl:if test="db:PARTY_SITE_USE_ID">
                      <comm:ID>
                        <xsl:value-of select="db:PARTY_SITE_USE_ID"/>
                      </comm:ID>
                    </xsl:if>
                    <xsl:if test="db:SITE_USE_TYPE">
                      <comm:SiteUse>
                        <xsl:value-of select="db:SITE_USE_TYPE"/>
                      </comm:SiteUse>
                    </xsl:if>
                    <xsl:if test="db:DESCRIPTION">
                      <comm:Description>
                        <xsl:value-of select="db:DESCRIPTION"/>
                      </comm:Description>
                    </xsl:if>
                  </comm:Purpose>
                </xsl:for-each>
              </comm:Purposes>
            </comm:Address>
          </comm:PrimaryInstitution>
        </xsl:if>
        <comm:Attribute1>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:ATTRIBUTE1"/>
        </comm:Attribute1>
        <comm:Attribute2>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:ATTRIBUTE2"/>
        </comm:Attribute2>
        <comm:Attribute3>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:ATTRIBUTE3"/>
        </comm:Attribute3>
        <comm:Attribute4>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:ATTRIBUTE4"/>
        </comm:Attribute4>
        <comm:Attribute5>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:ATTRIBUTE5"/>
        </comm:Attribute5>
        <comm:Attribute6>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:ATTRIBUTE6"/>
        </comm:Attribute6>
        <comm:Attribute7>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:ATTRIBUTE7"/>
        </comm:Attribute7>
        <comm:Attribute8>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:ATTRIBUTE8"/>
        </comm:Attribute8>
        <comm:Attribute9>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:ATTRIBUTE9"/>
        </comm:Attribute9>
        <comm:Attribute10>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:ATTRIBUTE10"/>
        </comm:Attribute10>
        <comm:Attribute11>
          <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:ATTRIBUTE11"/>
        </comm:Attribute11>
        <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS">
          <comm:PreferredAddress>
            <comm:Address>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:COUNTRY">
                <comm:Country>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:COUNTRY"/>
                </comm:Country>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ADDRESS1">
                <comm:Address1>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ADDRESS1"/>
                </comm:Address1>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ADDRESS2">
                <comm:Address2>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ADDRESS2"/>
                </comm:Address2>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ADDRESS3">
                <comm:Address3>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ADDRESS3"/>
                </comm:Address3>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ADDRESS4">
                <comm:Address4>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ADDRESS4"/>
                </comm:Address4>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:CITY">
                <comm:City>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:CITY"/>
                </comm:City>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:STATE">
                <comm:State>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:STATE"/>
                </comm:State>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:PROVINCE">
                <comm:Province>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:PROVINCE"/>
                </comm:Province>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:COUNTY">
                <comm:County>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:COUNTY"/>
                </comm:County>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:POSTALCODE">
                <comm:PostalCode>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:POSTALCODE"/>
                </comm:PostalCode>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ADDRESSNAME">
                <comm:AddressName>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ADDRESSNAME"/>
                </comm:AddressName>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:IDENTIFINGFLAG">
                <comm:IdentifingFlag>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:IDENTIFINGFLAG"/>
                </comm:IdentifingFlag>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:PREFERREDFLAG">
                <comm:PreferredFlag>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:PREFERREDFLAG"/>
                </comm:PreferredFlag>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:STATUS">
                <comm:Status>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:STATUS"/>
                </comm:Status>
              </xsl:if>
              <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ISADDRESSVALIDATED">
                <comm:IsAddressValidated>
                  <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:ISADDRESSVALIDATED"/>
                </comm:IsAddressValidated>
              </xsl:if>
              <comm:Purposes>
                <xsl:for-each select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:ADDRESS/db:PURPOSES/db:PURPOSES_ITEM">
                  <comm:Purpose>
                    <xsl:if test="db:PARTY_SITE_USE_ID">
                      <comm:ID>
                        <xsl:value-of select="db:PARTY_SITE_USE_ID"/>
                      </comm:ID>
                    </xsl:if>
                    <xsl:if test="db:DESCRIPTION">
                      <comm:Description>
                        <xsl:value-of select="db:DESCRIPTION"/>
                      </comm:Description>
                    </xsl:if>
                  </comm:Purpose>
                </xsl:for-each>
              </comm:Purposes>
            </comm:Address>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC">
              <comm:InstitutionInfo>
                <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:PARTY_ID">
                  <comm:InstitutionID>
                    <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:PARTY_ID"/>
                  </comm:InstitutionID>
                </xsl:if>
                <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:PARTY_NUMBER">
                  <comm:InstitutionNumber>
                    <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:PARTY_NUMBER"/>
                  </comm:InstitutionNumber>
                </xsl:if>
                <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:PARTY_NAME">
                  <comm:InstitutionName>
                    <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:PARTY_NAME"/>
                  </comm:InstitutionName>
                </xsl:if>
                <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:LONG_BUSINESS_NAME">
                  <comm:InstitutionLBN>
                    <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:LONG_BUSINESS_NAME"/>
                  </comm:InstitutionLBN>
                </xsl:if>
                <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:CLIA_NUMBER">
                  <comm:CLIANumber>
                    <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:CLIA_NUMBER"/>
                  </comm:CLIANumber>
                </xsl:if>
                <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:LAP_FLAG">
                  <comm:LAPFlag>
                    <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:LAP_FLAG"/>
                  </comm:LAPFlag>
                </xsl:if>
                <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:HU_FLAG">
                  <comm:HUFlag>
                    <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_ADDRESS/db:INSTITUTION_REC/db:HU_FLAG"/>
                  </comm:HUFlag>
                </xsl:if>
              </comm:InstitutionInfo>
            </xsl:if>
          </comm:PreferredAddress>
        </xsl:if>
        <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_EMAIL">
          <comm:PreferredEmail>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_EMAIL/db:CONTACT_POINT_ID">
              <comm:ID>
                <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_EMAIL/db:CONTACT_POINT_ID"/>
              </comm:ID>
            </xsl:if>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_EMAIL/db:EMAIL_ADDRESS">
              <comm:EmailAddress>
                <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_EMAIL/db:EMAIL_ADDRESS"/>
              </comm:EmailAddress>
            </xsl:if>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_EMAIL/db:EMAIL_FORMAT">
              <comm:EmailFormat>
                <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_EMAIL/db:EMAIL_FORMAT"/>
              </comm:EmailFormat>
            </xsl:if>
          </comm:PreferredEmail>
        </xsl:if>
        <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE">
          <comm:PreferredPhone>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:CONTACT_POINT_ID">
              <comm:ID>
                <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:CONTACT_POINT_ID"/>
              </comm:ID>
            </xsl:if>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_COUNTRY_CODE">
              <comm:CountryCode>
                <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_COUNTRY_CODE"/>
              </comm:CountryCode>
            </xsl:if>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_AREA_CODE">
              <comm:AreaCode>
                <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_AREA_CODE"/>
              </comm:AreaCode>
            </xsl:if>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_EXTENSION">
              <comm:Extension>
                <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_EXTENSION"/>
              </comm:Extension>
            </xsl:if>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_NUMBER">
              <comm:PhoneNumber>
                <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_NUMBER"/>
              </comm:PhoneNumber>
            </xsl:if>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:RAW_PHONE_NUMBER">
              <comm:RawPhoneNumber>
                <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:RAW_PHONE_NUMBER"/>
              </comm:RawPhoneNumber>
            </xsl:if>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_NUMBER_ALL">
              <comm:PhoneNumberAll>
                <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_NUMBER_ALL"/>
              </comm:PhoneNumberAll>
            </xsl:if>
            <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_LINE_TYPE">
              <comm:PhoneLineType>
                <xsl:value-of select="/db:OutputParameters/db:X_PERSON_DATA/db:PREFERRED_PHONE/db:PHONE_LINE_TYPE"/>
              </comm:PhoneLineType>
            </xsl:if>
          </comm:PreferredPhone>
        </xsl:if>
        <xsl:if test="/db:OutputParameters/db:X_PERSON_DATA/db:CREDENTIALS">
          <comm:Credentials>
            <xsl:for-each select="/db:OutputParameters/db:X_PERSON_DATA/db:CREDENTIALS/db:CREDENTIALS_ITEM">
              <comm:Credential>
                <xsl:if test="db:ID">
                  <comm:ID>
                    <xsl:value-of select="db:ID"/>
                  </comm:ID>
                </xsl:if>
                <xsl:if test="db:VALUE">
                  <comm:Value>
                    <xsl:value-of select="db:VALUE"/>
                  </comm:Value>
                </xsl:if>
                <xsl:if test="db:STATUS">
                  <comm:Status>
                    <xsl:value-of select="db:STATUS"/>
                  </comm:Status>
                </xsl:if>
              </comm:Credential>
            </xsl:for-each>
          </comm:Credentials>
        </xsl:if>
        <comm:Specialities>
          <xsl:for-each select="/db:OutputParameters/db:X_PERSON_DATA/db:SPECIALITIES/db:SPECIALITIES_ITEM">
            <comm:Speciality>
              <xsl:if test="db:ID">
                <comm:ID>
                  <xsl:value-of select="db:ID"/>
                </comm:ID>
              </xsl:if>
              <xsl:if test="db:SPECIALITY_VALUE">
                <comm:SpecialityValue>
                  <xsl:value-of select="db:SPECIALITY_VALUE"/>
                </comm:SpecialityValue>
              </xsl:if>
              <xsl:if test="db:SPECIALITY_NAME">
                <comm:SpecialityName>
                  <xsl:value-of select="db:SPECIALITY_NAME"/>
                </comm:SpecialityName>
              </xsl:if>
              <xsl:if test="db:YEARS_OF_EXPERIENCE">
                <comm:YearsOfExperience>
                  <xsl:value-of select="db:YEARS_OF_EXPERIENCE"/>
                </comm:YearsOfExperience>
              </xsl:if>
              <xsl:if test="db:CURRENTLY_TESTING_FLAG">
                <comm:CurrentlyTestingFlag>
                  <xsl:value-of select="db:CURRENTLY_TESTING_FLAG"/>
                </comm:CurrentlyTestingFlag>
              </xsl:if>
              <xsl:if test="db:ABILITY_TO_INSPECT_RANK">
                <comm:AbilityToInspectRank>
                  <xsl:value-of select="db:ABILITY_TO_INSPECT_RANK"/>
                </comm:AbilityToInspectRank>
              </xsl:if>
              <xsl:if test="db:ABILITY_TO_INSPECT_DESC">
                <comm:AbilityToInspectDescription/>
              </xsl:if>
              <xsl:if test="db:STATUS">
                <comm:Status>
                  <xsl:value-of select="db:STATUS"/>
                </comm:Status>
              </xsl:if>
            </comm:Speciality>
          </xsl:for-each>
        </comm:Specialities>
      </cp:Person>
    </cp:ChangeRequest>
  </xsl:template>
</xsl:stylesheet>
